[workspace]

members = [
  "packages/smd_macro",
  "packages/smithy_types",
  "packages/smd_tests",
  "packages/smithy_core",
  "packages/smithy"
]

[replace]
"proc-macro2:0.4.24" = { path = "./packages/proc-macro2" }
