[workspace]

members = [
  "crates/smd_macro",
  "crates/smithy_types",
  "crates/smd_tests",
  "crates/smithy_core",
  "crates/smithy",
  "crates/smithy_forge"
]

[replace]
"proc-macro2:0.4.24" = { path = "./crates/proc-macro2" }
