[package]
name = "smd_tests"
version = "0.0.2"
authors = ["Robert Balicki <robert.balicki@gmail.com>"]
edition = "2018"

[dependencies]
smd_macro = { path = "../smd_macro", version = "0.0.2" }
smithy_types = { path = "../smithy_types", version = "0.0.2" }
smithy = { path = "../smithy", version = "0.0.2" }
wasm-bindgen = { version = "0.2.28", features = ["nightly"] }
web-sys = { version = "0.3.5", features = [] }

[workspace]
members = ["."]
