[package]
name = "smd_tests"
version = "0.1.0"
authors = ["Robert Balicki <robert.balicki@gmail.com>"]
edition = "2018"

[dependencies]
smd_macro = { path = "../smd_macro" }
smithy_types = { path = "../smithy_types" }
smithy = { path = "../smithy" }
wasm-bindgen = { version = "0.2.28", features = ["nightly"] }
web-sys = { version = "0.3.5", features = [] }

[workspace]
members = ["."]

[replace]
"proc-macro2:0.4.24" = { path = "../proc-macro2" }
