[package]
name = "smithy_core"
version = "0.1.0"
authors = ["Robert Balicki <robert.balicki@gmail.com>"]
description = "A Rust framework for front-end web development"
edition = "2018"
keywords = ["web", "asmjs", "webasm", "javascript", "webassembly", "wasm"]
categories = ["gui", "web-programming"]
repository = "https://github.com/rbalicki2/smithy"
homepage = "https://github.com/rbalicki2/smithy"

[dependencies]
smd_macro = { path = "../smd_macro" }
smithy_types = { path = "../smithy_types" }
wasm-bindgen = { version = "0.2.28", features = ["nightly"] }
web-sys = { version = "0.3.5", features = [
  "Element",

  # element events
  "MouseEvent",

  # window events
  "HashChangeEvent",
] }
js-sys = "0.3.5"
futures = "0.1.25"
wasm-bindgen-futures = "0.3.5"
