[package]
name = "smd_macro"
version = "0.1.0"
authors = ["Robert Balicki <robert.balicki@gmail.com>"]
edition = "2018"

[dependencies]
smithy_types = { path = "../smithy_types" }
# proc-macro2 = { path = "../proc-macro2" }
# quote = { path = "../quote" }
quote = "0.6.10"
proc-macro2 = { version = "0.4.24", features = ["nightly"] }
nom = "4.1.1"

[lib]
proc-macro = true
