[package]
name = "smd_macro"
version = "0.0.2"
authors = ["Robert Balicki <robert.balicki@gmail.com>"]
edition = "2018"

[dependencies]
smithy_types = { path = "../smithy_types", version = "0.0.2" }
# proc-macro2 = { path = "../proc-macro2" }
# quote = { path = "../quote" }
quote = "0.6.10"
proc-macro2 = { version = "0.4.27", features = ["nightly"] }
nom = "4.1.1"
lazy_static = "1.2.0"

[lib]
proc-macro = true

[features]
smd-logs = []

[replace]
"proc-macro2:0.4.27" = { path = "../proc-macro2" }